describe Token, type: :model do
  describe 'name' do
    it 'is autogenerated, 6 characters long' do
      token = build(:token, name: nil)
      expect(token).to be_valid
      expect(token.name.length).to eq 6
    end

    context 'duplicate tokens' do
      before do
        allow_any_instance_of(Token).to receive(:random_token)
          .and_return 'ABC123', 'DEF456'
      end
      it 'handles them like a boss' do
        2.times { create(:token) }
        tokens = Token.pluck(:name)
        expect(tokens).to eq ['ABC123', 'DEF456']
      end
    end
  end

  describe 'available' do
    before do
      @token_1 = create(:token)
      @token_2 = create(:token, user: create(:user))
    end
    it 'lists only tokens without associated users' do
      expect(Token.available).to eq [@token_1]
    end
  end
end
