describe Token, type: :model do
  describe 'name' do
    it 'is autogenerated, 5-6 characters long' do
      token = build(:token, name: nil)
      expect(token).to be_valid
      expect(token.name.length).to be >= 5
    end

    context 'duplicate tokens' do
      before do
        allow_any_instance_of(Token).to receive(:random_token)
          .and_return 'ABC123', 'DEF456'
      end
      it 'handles them like a boss' do
        2.times { create(:token) }
        tokens = Token.pluck(:name)
        expect(tokens).to eq ['ABC123', 'DEF456']
      end
    end
  end
end
