default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  timeout: 5000

development:
  <<: *default
  database: felix_development

test:
  <<: *default
  database: felix_test

production:
  <<: *default
  database: felix_production
